version: '3'
services:
  proxy:
    image: 'rydang/cryptdb-proxy'
    container_name: 'cryptdb_proxy'
    ports:
      - 3399:3399
    depends_on:
      - database
    networks:
      - cryptdb_network
    stdin_open: true
    tty: true
    command: ./wait-for-it.sh database:3306 -s -- ./cdbserver.sh database
  database:
    image: 'rydang/cryptdb-server'
    container_name: 'mysql_server'
    ports:
      - 3306:3306
    volumes:
        - mysql_db:/var/lib/mysql
    networks: 
      - cryptdb_network
networks:
  cryptdb_network:
volumes:
  mysql_db:
